package server

import (
	"context"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	echoSwagger "github.com/swaggo/echo-swagger"
	_ "github.com/swaggo/echo-swagger/example/docs" // docs is generated by Swag CLI, you have to import it.
)

type server struct {
	addr string
	e    *echo.Echo
}

func New(addr string) *server {
	return &server{addr: addr}
}

// @title API Веб-сервера
// @version 1.0
// @description Веб-сервер - сервер, перенаправляющий запросы от бота к другим сервисам
func (s *server) Serve() error {
	e := echo.New()

	e.Use(middleware.Logger())
	e.Use(middleware.Recover())

	e.GET("/health", s.health)
	e.GET("/swagger/*", echoSwagger.WrapHandler)

	s.e = e

	return e.Start(s.addr)
}

func (s *server) Shutdown(ctx context.Context) error {
	return s.e.Shutdown(ctx)
}
