package server

import (
	"context"
	"strings"

	_ "webserver/docs" // docs is generated by Swag CLI, you have to import it.
	"webserver/internal/service/note"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	echoSwagger "github.com/swaggo/echo-swagger"
)

type server struct {
	addr string
	e    *echo.Echo

	// services
	note *note.Note
}

func New(addr string, note *note.Note) *server {
	return &server{addr: addr, note: note}
}

func (s *server) Serve() error {
	e := echo.New()

	skipper := func(c echo.Context) bool {
		return strings.Contains(c.Request().URL.Path, "swagger")
	}

	e.Use(middleware.LoggerWithConfig(middleware.LoggerConfig{
		Skipper: skipper,
	}))

	e.Use(middleware.RecoverWithConfig(middleware.RecoverConfig{Skipper: skipper}))

	e.GET("/health", s.health)
	e.GET("/swagger/*", echoSwagger.WrapHandler)

	notes := e.Group("notes")

	notes.GET("/:id", s.notesByUserID)
	notes.POST("/create", s.createNote)

	s.e = e

	return e.Start(s.addr)
}

func (s *server) Shutdown(ctx context.Context) error {
	return s.e.Shutdown(ctx)
}
