// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "webserver/internal/model"

	gomock "github.com/golang/mock/gomock"
)

// MocknoteRepo is a mock of noteRepo interface.
type MocknoteRepo struct {
	ctrl     *gomock.Controller
	recorder *MocknoteRepoMockRecorder
}

// MocknoteRepoMockRecorder is the mock recorder for MocknoteRepo.
type MocknoteRepoMockRecorder struct {
	mock *MocknoteRepo
}

// NewMocknoteRepo creates a new mock instance.
func NewMocknoteRepo(ctrl *gomock.Controller) *MocknoteRepo {
	mock := &MocknoteRepo{ctrl: ctrl}
	mock.recorder = &MocknoteRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknoteRepo) EXPECT() *MocknoteRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MocknoteRepo) Create(ctx context.Context, note model.CreateNoteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, note)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MocknoteRepoMockRecorder) Create(ctx, note interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocknoteRepo)(nil).Create), ctx, note)
}

// GetAllBySpaceID mocks base method.
func (m *MocknoteRepo) GetAllBySpaceID(ctx context.Context, spaceID int64) ([]model.GetNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBySpaceID", ctx, spaceID)
	ret0, _ := ret[0].([]model.GetNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBySpaceID indicates an expected call of GetAllBySpaceID.
func (mr *MocknoteRepoMockRecorder) GetAllBySpaceID(ctx, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBySpaceID", reflect.TypeOf((*MocknoteRepo)(nil).GetAllBySpaceID), ctx, spaceID)
}

// GetAllbySpaceIDFull mocks base method.
func (m *MocknoteRepo) GetAllbySpaceIDFull(ctx context.Context, spaceID int64) ([]model.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllbySpaceIDFull", ctx, spaceID)
	ret0, _ := ret[0].([]model.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllbySpaceIDFull indicates an expected call of GetAllbySpaceIDFull.
func (mr *MocknoteRepoMockRecorder) GetAllbySpaceIDFull(ctx, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllbySpaceIDFull", reflect.TypeOf((*MocknoteRepo)(nil).GetAllbySpaceIDFull), ctx, spaceID)
}
