// Code generated by MockGen. DO NOT EDIT.
// Source: ./space.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "webserver/internal/model"
	rabbit "webserver/internal/model/rabbit"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockspaceRepo is a mock of spaceRepo interface.
type MockspaceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockspaceRepoMockRecorder
}

// MockspaceRepoMockRecorder is the mock recorder for MockspaceRepo.
type MockspaceRepoMockRecorder struct {
	mock *MockspaceRepo
}

// NewMockspaceRepo creates a new mock instance.
func NewMockspaceRepo(ctrl *gomock.Controller) *MockspaceRepo {
	mock := &MockspaceRepo{ctrl: ctrl}
	mock.recorder = &MockspaceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockspaceRepo) EXPECT() *MockspaceRepoMockRecorder {
	return m.recorder
}

// CheckParticipant mocks base method.
func (m *MockspaceRepo) CheckParticipant(ctx context.Context, userID int64, spaceID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckParticipant", ctx, userID, spaceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckParticipant indicates an expected call of CheckParticipant.
func (mr *MockspaceRepoMockRecorder) CheckParticipant(ctx, userID, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckParticipant", reflect.TypeOf((*MockspaceRepo)(nil).CheckParticipant), ctx, userID, spaceID)
}

// GetAllNotesBySpaceID mocks base method.
func (m *MockspaceRepo) GetAllNotesBySpaceID(ctx context.Context, spaceID uuid.UUID) ([]model.GetNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNotesBySpaceID", ctx, spaceID)
	ret0, _ := ret[0].([]model.GetNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNotesBySpaceID indicates an expected call of GetAllNotesBySpaceID.
func (mr *MockspaceRepoMockRecorder) GetAllNotesBySpaceID(ctx, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNotesBySpaceID", reflect.TypeOf((*MockspaceRepo)(nil).GetAllNotesBySpaceID), ctx, spaceID)
}

// GetAllNotesBySpaceIDFull mocks base method.
func (m *MockspaceRepo) GetAllNotesBySpaceIDFull(ctx context.Context, spaceID uuid.UUID) ([]model.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNotesBySpaceIDFull", ctx, spaceID)
	ret0, _ := ret[0].([]model.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNotesBySpaceIDFull indicates an expected call of GetAllNotesBySpaceIDFull.
func (mr *MockspaceRepoMockRecorder) GetAllNotesBySpaceIDFull(ctx, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNotesBySpaceIDFull", reflect.TypeOf((*MockspaceRepo)(nil).GetAllNotesBySpaceIDFull), ctx, spaceID)
}

// GetNoteByID mocks base method.
func (m *MockspaceRepo) GetNoteByID(ctx context.Context, noteID uuid.UUID) (model.GetNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoteByID", ctx, noteID)
	ret0, _ := ret[0].(model.GetNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNoteByID indicates an expected call of GetNoteByID.
func (mr *MockspaceRepoMockRecorder) GetNoteByID(ctx, noteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoteByID", reflect.TypeOf((*MockspaceRepo)(nil).GetNoteByID), ctx, noteID)
}

// GetNotesByType mocks base method.
func (m *MockspaceRepo) GetNotesByType(ctx context.Context, spaceID uuid.UUID, noteType model.NoteType) ([]model.GetNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotesByType", ctx, spaceID, noteType)
	ret0, _ := ret[0].([]model.GetNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotesByType indicates an expected call of GetNotesByType.
func (mr *MockspaceRepoMockRecorder) GetNotesByType(ctx, spaceID, noteType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotesByType", reflect.TypeOf((*MockspaceRepo)(nil).GetNotesByType), ctx, spaceID, noteType)
}

// GetNotesTypes mocks base method.
func (m *MockspaceRepo) GetNotesTypes(ctx context.Context, spaceID uuid.UUID) ([]model.NoteTypeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotesTypes", ctx, spaceID)
	ret0, _ := ret[0].([]model.NoteTypeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotesTypes indicates an expected call of GetNotesTypes.
func (mr *MockspaceRepoMockRecorder) GetNotesTypes(ctx, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotesTypes", reflect.TypeOf((*MockspaceRepo)(nil).GetNotesTypes), ctx, spaceID)
}

// GetSpaceByID mocks base method.
func (m *MockspaceRepo) GetSpaceByID(ctx context.Context, id uuid.UUID) (model.Space, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpaceByID", ctx, id)
	ret0, _ := ret[0].(model.Space)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpaceByID indicates an expected call of GetSpaceByID.
func (mr *MockspaceRepoMockRecorder) GetSpaceByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpaceByID", reflect.TypeOf((*MockspaceRepo)(nil).GetSpaceByID), ctx, id)
}

// SearchNoteByText mocks base method.
func (m *MockspaceRepo) SearchNoteByText(ctx context.Context, req model.SearchNoteByTextRequest) ([]model.GetNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchNoteByText", ctx, req)
	ret0, _ := ret[0].([]model.GetNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchNoteByText indicates an expected call of SearchNoteByText.
func (mr *MockspaceRepoMockRecorder) SearchNoteByText(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchNoteByText", reflect.TypeOf((*MockspaceRepo)(nil).SearchNoteByText), ctx, req)
}

// MockspaceCache is a mock of spaceCache interface.
type MockspaceCache struct {
	ctrl     *gomock.Controller
	recorder *MockspaceCacheMockRecorder
}

// MockspaceCacheMockRecorder is the mock recorder for MockspaceCache.
type MockspaceCacheMockRecorder struct {
	mock *MockspaceCache
}

// NewMockspaceCache creates a new mock instance.
func NewMockspaceCache(ctrl *gomock.Controller) *MockspaceCache {
	mock := &MockspaceCache{ctrl: ctrl}
	mock.recorder = &MockspaceCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockspaceCache) EXPECT() *MockspaceCacheMockRecorder {
	return m.recorder
}

// GetSpaceByID mocks base method.
func (m *MockspaceCache) GetSpaceByID(ctx context.Context, id uuid.UUID) (model.Space, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpaceByID", ctx, id)
	ret0, _ := ret[0].(model.Space)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpaceByID indicates an expected call of GetSpaceByID.
func (mr *MockspaceCacheMockRecorder) GetSpaceByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpaceByID", reflect.TypeOf((*MockspaceCache)(nil).GetSpaceByID), ctx, id)
}

// MockdbWorker is a mock of dbWorker interface.
type MockdbWorker struct {
	ctrl     *gomock.Controller
	recorder *MockdbWorkerMockRecorder
}

// MockdbWorkerMockRecorder is the mock recorder for MockdbWorker.
type MockdbWorkerMockRecorder struct {
	mock *MockdbWorker
}

// NewMockdbWorker creates a new mock instance.
func NewMockdbWorker(ctrl *gomock.Controller) *MockdbWorker {
	mock := &MockdbWorker{ctrl: ctrl}
	mock.recorder = &MockdbWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdbWorker) EXPECT() *MockdbWorkerMockRecorder {
	return m.recorder
}

// CreateNote mocks base method.
func (m *MockdbWorker) CreateNote(ctx context.Context, req rabbit.CreateNoteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockdbWorkerMockRecorder) CreateNote(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockdbWorker)(nil).CreateNote), ctx, req)
}

// DeleteNote mocks base method.
func (m *MockdbWorker) DeleteNote(ctx context.Context, req rabbit.DeleteNoteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockdbWorkerMockRecorder) DeleteNote(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockdbWorker)(nil).DeleteNote), ctx, req)
}

// UpdateNote mocks base method.
func (m *MockdbWorker) UpdateNote(ctx context.Context, req rabbit.UpdateNoteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNote", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MockdbWorkerMockRecorder) UpdateNote(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockdbWorker)(nil).UpdateNote), ctx, req)
}
