// Code generated by MockGen. DO NOT EDIT.
// Source: ./space.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "webserver/internal/model"

	gomock "github.com/golang/mock/gomock"
)

// MockspaceRepo is a mock of spaceRepo interface.
type MockspaceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockspaceRepoMockRecorder
}

// MockspaceRepoMockRecorder is the mock recorder for MockspaceRepo.
type MockspaceRepoMockRecorder struct {
	mock *MockspaceRepo
}

// NewMockspaceRepo creates a new mock instance.
func NewMockspaceRepo(ctrl *gomock.Controller) *MockspaceRepo {
	mock := &MockspaceRepo{ctrl: ctrl}
	mock.recorder = &MockspaceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockspaceRepo) EXPECT() *MockspaceRepoMockRecorder {
	return m.recorder
}

// CreateNote mocks base method.
func (m *MockspaceRepo) CreateNote(ctx context.Context, note model.CreateNoteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, note)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockspaceRepoMockRecorder) CreateNote(ctx, note interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockspaceRepo)(nil).CreateNote), ctx, note)
}

// GetAllBySpaceID mocks base method.
func (m *MockspaceRepo) GetAllBySpaceID(ctx context.Context, spaceID int64) ([]model.GetNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBySpaceID", ctx, spaceID)
	ret0, _ := ret[0].([]model.GetNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBySpaceID indicates an expected call of GetAllBySpaceID.
func (mr *MockspaceRepoMockRecorder) GetAllBySpaceID(ctx, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBySpaceID", reflect.TypeOf((*MockspaceRepo)(nil).GetAllBySpaceID), ctx, spaceID)
}

// GetAllbySpaceIDFull mocks base method.
func (m *MockspaceRepo) GetAllbySpaceIDFull(ctx context.Context, spaceID int64) ([]model.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllbySpaceIDFull", ctx, spaceID)
	ret0, _ := ret[0].([]model.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllbySpaceIDFull indicates an expected call of GetAllbySpaceIDFull.
func (mr *MockspaceRepoMockRecorder) GetAllbySpaceIDFull(ctx, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllbySpaceIDFull", reflect.TypeOf((*MockspaceRepo)(nil).GetAllbySpaceIDFull), ctx, spaceID)
}

// GetSpaceByID mocks base method.
func (m *MockspaceRepo) GetSpaceByID(ctx context.Context, id int) (model.Space, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpaceByID", ctx, id)
	ret0, _ := ret[0].(model.Space)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpaceByID indicates an expected call of GetSpaceByID.
func (mr *MockspaceRepoMockRecorder) GetSpaceByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpaceByID", reflect.TypeOf((*MockspaceRepo)(nil).GetSpaceByID), ctx, id)
}
