// Code generated by MockGen. DO NOT EDIT.
// Source: ./handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "webserver/internal/model"
	rabbit "webserver/internal/model/rabbit"

	jwt "github.com/golang-jwt/jwt/v5"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockspaceService is a mock of spaceService interface.
type MockspaceService struct {
	ctrl     *gomock.Controller
	recorder *MockspaceServiceMockRecorder
}

// MockspaceServiceMockRecorder is the mock recorder for MockspaceService.
type MockspaceServiceMockRecorder struct {
	mock *MockspaceService
}

// NewMockspaceService creates a new mock instance.
func NewMockspaceService(ctrl *gomock.Controller) *MockspaceService {
	mock := &MockspaceService{ctrl: ctrl}
	mock.recorder = &MockspaceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockspaceService) EXPECT() *MockspaceServiceMockRecorder {
	return m.recorder
}

// AddParticipant mocks base method.
func (m *MockspaceService) AddParticipant(ctx context.Context, req rabbit.AddParticipantRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddParticipant", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddParticipant indicates an expected call of AddParticipant.
func (mr *MockspaceServiceMockRecorder) AddParticipant(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddParticipant", reflect.TypeOf((*MockspaceService)(nil).AddParticipant), ctx, req)
}

// CheckInvitation mocks base method.
func (m *MockspaceService) CheckInvitation(ctx context.Context, from, to int64, spaceID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckInvitation", ctx, from, to, spaceID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckInvitation indicates an expected call of CheckInvitation.
func (mr *MockspaceServiceMockRecorder) CheckInvitation(ctx, from, to, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckInvitation", reflect.TypeOf((*MockspaceService)(nil).CheckInvitation), ctx, from, to, spaceID)
}

// CreateNote mocks base method.
func (m *MockspaceService) CreateNote(ctx context.Context, note rabbit.CreateNoteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, note)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockspaceServiceMockRecorder) CreateNote(ctx, note interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockspaceService)(nil).CreateNote), ctx, note)
}

// CreateSpace mocks base method.
func (m *MockspaceService) CreateSpace(ctx context.Context, req rabbit.CreateSpaceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSpace", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSpace indicates an expected call of CreateSpace.
func (mr *MockspaceServiceMockRecorder) CreateSpace(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSpace", reflect.TypeOf((*MockspaceService)(nil).CreateSpace), ctx, req)
}

// DeleteAllNotes mocks base method.
func (m *MockspaceService) DeleteAllNotes(ctx context.Context, req rabbit.DeleteAllNotesRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllNotes", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllNotes indicates an expected call of DeleteAllNotes.
func (mr *MockspaceServiceMockRecorder) DeleteAllNotes(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllNotes", reflect.TypeOf((*MockspaceService)(nil).DeleteAllNotes), ctx, req)
}

// DeleteNote mocks base method.
func (m *MockspaceService) DeleteNote(ctx context.Context, req rabbit.DeleteNoteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockspaceServiceMockRecorder) DeleteNote(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockspaceService)(nil).DeleteNote), ctx, req)
}

// GetAllNotesBySpaceID mocks base method.
func (m *MockspaceService) GetAllNotesBySpaceID(ctx context.Context, spaceID uuid.UUID) ([]model.GetNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNotesBySpaceID", ctx, spaceID)
	ret0, _ := ret[0].([]model.GetNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNotesBySpaceID indicates an expected call of GetAllNotesBySpaceID.
func (mr *MockspaceServiceMockRecorder) GetAllNotesBySpaceID(ctx, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNotesBySpaceID", reflect.TypeOf((*MockspaceService)(nil).GetAllNotesBySpaceID), ctx, spaceID)
}

// GetAllNotesBySpaceIDFull mocks base method.
func (m *MockspaceService) GetAllNotesBySpaceIDFull(ctx context.Context, spaceID uuid.UUID) ([]model.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNotesBySpaceIDFull", ctx, spaceID)
	ret0, _ := ret[0].([]model.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNotesBySpaceIDFull indicates an expected call of GetAllNotesBySpaceIDFull.
func (mr *MockspaceServiceMockRecorder) GetAllNotesBySpaceIDFull(ctx, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNotesBySpaceIDFull", reflect.TypeOf((*MockspaceService)(nil).GetAllNotesBySpaceIDFull), ctx, spaceID)
}

// GetNoteByID mocks base method.
func (m *MockspaceService) GetNoteByID(ctx context.Context, noteID uuid.UUID) (model.GetNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoteByID", ctx, noteID)
	ret0, _ := ret[0].(model.GetNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNoteByID indicates an expected call of GetNoteByID.
func (mr *MockspaceServiceMockRecorder) GetNoteByID(ctx, noteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoteByID", reflect.TypeOf((*MockspaceService)(nil).GetNoteByID), ctx, noteID)
}

// GetNotesByType mocks base method.
func (m *MockspaceService) GetNotesByType(ctx context.Context, spaceID uuid.UUID, noteType model.NoteType) ([]model.GetNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotesByType", ctx, spaceID, noteType)
	ret0, _ := ret[0].([]model.GetNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotesByType indicates an expected call of GetNotesByType.
func (mr *MockspaceServiceMockRecorder) GetNotesByType(ctx, spaceID, noteType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotesByType", reflect.TypeOf((*MockspaceService)(nil).GetNotesByType), ctx, spaceID, noteType)
}

// GetNotesTypes mocks base method.
func (m *MockspaceService) GetNotesTypes(ctx context.Context, spaceID uuid.UUID) ([]model.NoteTypeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotesTypes", ctx, spaceID)
	ret0, _ := ret[0].([]model.NoteTypeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotesTypes indicates an expected call of GetNotesTypes.
func (mr *MockspaceServiceMockRecorder) GetNotesTypes(ctx, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotesTypes", reflect.TypeOf((*MockspaceService)(nil).GetNotesTypes), ctx, spaceID)
}

// GetSpaceByID mocks base method.
func (m *MockspaceService) GetSpaceByID(ctx context.Context, id uuid.UUID) (model.Space, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpaceByID", ctx, id)
	ret0, _ := ret[0].(model.Space)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpaceByID indicates an expected call of GetSpaceByID.
func (mr *MockspaceServiceMockRecorder) GetSpaceByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpaceByID", reflect.TypeOf((*MockspaceService)(nil).GetSpaceByID), ctx, id)
}

// IsSpaceExists mocks base method.
func (m *MockspaceService) IsSpaceExists(ctx context.Context, spaceID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSpaceExists", ctx, spaceID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSpaceExists indicates an expected call of IsSpaceExists.
func (mr *MockspaceServiceMockRecorder) IsSpaceExists(ctx, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSpaceExists", reflect.TypeOf((*MockspaceService)(nil).IsSpaceExists), ctx, spaceID)
}

// IsSpacePersonal mocks base method.
func (m *MockspaceService) IsSpacePersonal(ctx context.Context, spaceID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSpacePersonal", ctx, spaceID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSpacePersonal indicates an expected call of IsSpacePersonal.
func (mr *MockspaceServiceMockRecorder) IsSpacePersonal(ctx, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSpacePersonal", reflect.TypeOf((*MockspaceService)(nil).IsSpacePersonal), ctx, spaceID)
}

// IsUserInSpace mocks base method.
func (m *MockspaceService) IsUserInSpace(ctx context.Context, userID int64, spaceID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserInSpace", ctx, userID, spaceID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserInSpace indicates an expected call of IsUserInSpace.
func (mr *MockspaceServiceMockRecorder) IsUserInSpace(ctx, userID, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserInSpace", reflect.TypeOf((*MockspaceService)(nil).IsUserInSpace), ctx, userID, spaceID)
}

// SearchNoteByText mocks base method.
func (m *MockspaceService) SearchNoteByText(ctx context.Context, req model.SearchNoteByTextRequest) ([]model.GetNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchNoteByText", ctx, req)
	ret0, _ := ret[0].([]model.GetNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchNoteByText indicates an expected call of SearchNoteByText.
func (mr *MockspaceServiceMockRecorder) SearchNoteByText(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchNoteByText", reflect.TypeOf((*MockspaceService)(nil).SearchNoteByText), ctx, req)
}

// UpdateNote mocks base method.
func (m *MockspaceService) UpdateNote(ctx context.Context, update rabbit.UpdateNoteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNote", ctx, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MockspaceServiceMockRecorder) UpdateNote(ctx, update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockspaceService)(nil).UpdateNote), ctx, update)
}

// MockspaceCreator is a mock of spaceCreator interface.
type MockspaceCreator struct {
	ctrl     *gomock.Controller
	recorder *MockspaceCreatorMockRecorder
}

// MockspaceCreatorMockRecorder is the mock recorder for MockspaceCreator.
type MockspaceCreatorMockRecorder struct {
	mock *MockspaceCreator
}

// NewMockspaceCreator creates a new mock instance.
func NewMockspaceCreator(ctrl *gomock.Controller) *MockspaceCreator {
	mock := &MockspaceCreator{ctrl: ctrl}
	mock.recorder = &MockspaceCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockspaceCreator) EXPECT() *MockspaceCreatorMockRecorder {
	return m.recorder
}

// CreateSpace mocks base method.
func (m *MockspaceCreator) CreateSpace(ctx context.Context, req rabbit.CreateSpaceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSpace", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSpace indicates an expected call of CreateSpace.
func (mr *MockspaceCreatorMockRecorder) CreateSpace(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSpace", reflect.TypeOf((*MockspaceCreator)(nil).CreateSpace), ctx, req)
}

// MockspaceChecker is a mock of spaceChecker interface.
type MockspaceChecker struct {
	ctrl     *gomock.Controller
	recorder *MockspaceCheckerMockRecorder
}

// MockspaceCheckerMockRecorder is the mock recorder for MockspaceChecker.
type MockspaceCheckerMockRecorder struct {
	mock *MockspaceChecker
}

// NewMockspaceChecker creates a new mock instance.
func NewMockspaceChecker(ctrl *gomock.Controller) *MockspaceChecker {
	mock := &MockspaceChecker{ctrl: ctrl}
	mock.recorder = &MockspaceCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockspaceChecker) EXPECT() *MockspaceCheckerMockRecorder {
	return m.recorder
}

// CheckInvitation mocks base method.
func (m *MockspaceChecker) CheckInvitation(ctx context.Context, from, to int64, spaceID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckInvitation", ctx, from, to, spaceID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckInvitation indicates an expected call of CheckInvitation.
func (mr *MockspaceCheckerMockRecorder) CheckInvitation(ctx, from, to, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckInvitation", reflect.TypeOf((*MockspaceChecker)(nil).CheckInvitation), ctx, from, to, spaceID)
}

// IsSpaceExists mocks base method.
func (m *MockspaceChecker) IsSpaceExists(ctx context.Context, spaceID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSpaceExists", ctx, spaceID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSpaceExists indicates an expected call of IsSpaceExists.
func (mr *MockspaceCheckerMockRecorder) IsSpaceExists(ctx, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSpaceExists", reflect.TypeOf((*MockspaceChecker)(nil).IsSpaceExists), ctx, spaceID)
}

// IsSpacePersonal mocks base method.
func (m *MockspaceChecker) IsSpacePersonal(ctx context.Context, spaceID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSpacePersonal", ctx, spaceID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSpacePersonal indicates an expected call of IsSpacePersonal.
func (mr *MockspaceCheckerMockRecorder) IsSpacePersonal(ctx, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSpacePersonal", reflect.TypeOf((*MockspaceChecker)(nil).IsSpacePersonal), ctx, spaceID)
}

// IsUserInSpace mocks base method.
func (m *MockspaceChecker) IsUserInSpace(ctx context.Context, userID int64, spaceID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserInSpace", ctx, userID, spaceID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserInSpace indicates an expected call of IsUserInSpace.
func (mr *MockspaceCheckerMockRecorder) IsUserInSpace(ctx, userID, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserInSpace", reflect.TypeOf((*MockspaceChecker)(nil).IsUserInSpace), ctx, userID, spaceID)
}

// MockparticipantAdder is a mock of participantAdder interface.
type MockparticipantAdder struct {
	ctrl     *gomock.Controller
	recorder *MockparticipantAdderMockRecorder
}

// MockparticipantAdderMockRecorder is the mock recorder for MockparticipantAdder.
type MockparticipantAdderMockRecorder struct {
	mock *MockparticipantAdder
}

// NewMockparticipantAdder creates a new mock instance.
func NewMockparticipantAdder(ctrl *gomock.Controller) *MockparticipantAdder {
	mock := &MockparticipantAdder{ctrl: ctrl}
	mock.recorder = &MockparticipantAdderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockparticipantAdder) EXPECT() *MockparticipantAdderMockRecorder {
	return m.recorder
}

// AddParticipant mocks base method.
func (m *MockparticipantAdder) AddParticipant(ctx context.Context, req rabbit.AddParticipantRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddParticipant", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddParticipant indicates an expected call of AddParticipant.
func (mr *MockparticipantAdderMockRecorder) AddParticipant(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddParticipant", reflect.TypeOf((*MockparticipantAdder)(nil).AddParticipant), ctx, req)
}

// MockspaceGetter is a mock of spaceGetter interface.
type MockspaceGetter struct {
	ctrl     *gomock.Controller
	recorder *MockspaceGetterMockRecorder
}

// MockspaceGetterMockRecorder is the mock recorder for MockspaceGetter.
type MockspaceGetterMockRecorder struct {
	mock *MockspaceGetter
}

// NewMockspaceGetter creates a new mock instance.
func NewMockspaceGetter(ctrl *gomock.Controller) *MockspaceGetter {
	mock := &MockspaceGetter{ctrl: ctrl}
	mock.recorder = &MockspaceGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockspaceGetter) EXPECT() *MockspaceGetterMockRecorder {
	return m.recorder
}

// GetSpaceByID mocks base method.
func (m *MockspaceGetter) GetSpaceByID(ctx context.Context, id uuid.UUID) (model.Space, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpaceByID", ctx, id)
	ret0, _ := ret[0].(model.Space)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpaceByID indicates an expected call of GetSpaceByID.
func (mr *MockspaceGetterMockRecorder) GetSpaceByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpaceByID", reflect.TypeOf((*MockspaceGetter)(nil).GetSpaceByID), ctx, id)
}

// MocknoteCreator is a mock of noteCreator interface.
type MocknoteCreator struct {
	ctrl     *gomock.Controller
	recorder *MocknoteCreatorMockRecorder
}

// MocknoteCreatorMockRecorder is the mock recorder for MocknoteCreator.
type MocknoteCreatorMockRecorder struct {
	mock *MocknoteCreator
}

// NewMocknoteCreator creates a new mock instance.
func NewMocknoteCreator(ctrl *gomock.Controller) *MocknoteCreator {
	mock := &MocknoteCreator{ctrl: ctrl}
	mock.recorder = &MocknoteCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknoteCreator) EXPECT() *MocknoteCreatorMockRecorder {
	return m.recorder
}

// CreateNote mocks base method.
func (m *MocknoteCreator) CreateNote(ctx context.Context, note rabbit.CreateNoteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, note)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MocknoteCreatorMockRecorder) CreateNote(ctx, note interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MocknoteCreator)(nil).CreateNote), ctx, note)
}

// MocknoteUpdater is a mock of noteUpdater interface.
type MocknoteUpdater struct {
	ctrl     *gomock.Controller
	recorder *MocknoteUpdaterMockRecorder
}

// MocknoteUpdaterMockRecorder is the mock recorder for MocknoteUpdater.
type MocknoteUpdaterMockRecorder struct {
	mock *MocknoteUpdater
}

// NewMocknoteUpdater creates a new mock instance.
func NewMocknoteUpdater(ctrl *gomock.Controller) *MocknoteUpdater {
	mock := &MocknoteUpdater{ctrl: ctrl}
	mock.recorder = &MocknoteUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknoteUpdater) EXPECT() *MocknoteUpdaterMockRecorder {
	return m.recorder
}

// UpdateNote mocks base method.
func (m *MocknoteUpdater) UpdateNote(ctx context.Context, update rabbit.UpdateNoteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNote", ctx, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MocknoteUpdaterMockRecorder) UpdateNote(ctx, update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MocknoteUpdater)(nil).UpdateNote), ctx, update)
}

// MocknoteDeleter is a mock of noteDeleter interface.
type MocknoteDeleter struct {
	ctrl     *gomock.Controller
	recorder *MocknoteDeleterMockRecorder
}

// MocknoteDeleterMockRecorder is the mock recorder for MocknoteDeleter.
type MocknoteDeleterMockRecorder struct {
	mock *MocknoteDeleter
}

// NewMocknoteDeleter creates a new mock instance.
func NewMocknoteDeleter(ctrl *gomock.Controller) *MocknoteDeleter {
	mock := &MocknoteDeleter{ctrl: ctrl}
	mock.recorder = &MocknoteDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknoteDeleter) EXPECT() *MocknoteDeleterMockRecorder {
	return m.recorder
}

// DeleteAllNotes mocks base method.
func (m *MocknoteDeleter) DeleteAllNotes(ctx context.Context, req rabbit.DeleteAllNotesRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllNotes", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllNotes indicates an expected call of DeleteAllNotes.
func (mr *MocknoteDeleterMockRecorder) DeleteAllNotes(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllNotes", reflect.TypeOf((*MocknoteDeleter)(nil).DeleteAllNotes), ctx, req)
}

// DeleteNote mocks base method.
func (m *MocknoteDeleter) DeleteNote(ctx context.Context, req rabbit.DeleteNoteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MocknoteDeleterMockRecorder) DeleteNote(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MocknoteDeleter)(nil).DeleteNote), ctx, req)
}

// MocknoteGetter is a mock of noteGetter interface.
type MocknoteGetter struct {
	ctrl     *gomock.Controller
	recorder *MocknoteGetterMockRecorder
}

// MocknoteGetterMockRecorder is the mock recorder for MocknoteGetter.
type MocknoteGetterMockRecorder struct {
	mock *MocknoteGetter
}

// NewMocknoteGetter creates a new mock instance.
func NewMocknoteGetter(ctrl *gomock.Controller) *MocknoteGetter {
	mock := &MocknoteGetter{ctrl: ctrl}
	mock.recorder = &MocknoteGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknoteGetter) EXPECT() *MocknoteGetterMockRecorder {
	return m.recorder
}

// GetAllNotesBySpaceID mocks base method.
func (m *MocknoteGetter) GetAllNotesBySpaceID(ctx context.Context, spaceID uuid.UUID) ([]model.GetNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNotesBySpaceID", ctx, spaceID)
	ret0, _ := ret[0].([]model.GetNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNotesBySpaceID indicates an expected call of GetAllNotesBySpaceID.
func (mr *MocknoteGetterMockRecorder) GetAllNotesBySpaceID(ctx, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNotesBySpaceID", reflect.TypeOf((*MocknoteGetter)(nil).GetAllNotesBySpaceID), ctx, spaceID)
}

// GetAllNotesBySpaceIDFull mocks base method.
func (m *MocknoteGetter) GetAllNotesBySpaceIDFull(ctx context.Context, spaceID uuid.UUID) ([]model.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNotesBySpaceIDFull", ctx, spaceID)
	ret0, _ := ret[0].([]model.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNotesBySpaceIDFull indicates an expected call of GetAllNotesBySpaceIDFull.
func (mr *MocknoteGetterMockRecorder) GetAllNotesBySpaceIDFull(ctx, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNotesBySpaceIDFull", reflect.TypeOf((*MocknoteGetter)(nil).GetAllNotesBySpaceIDFull), ctx, spaceID)
}

// GetNoteByID mocks base method.
func (m *MocknoteGetter) GetNoteByID(ctx context.Context, noteID uuid.UUID) (model.GetNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoteByID", ctx, noteID)
	ret0, _ := ret[0].(model.GetNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNoteByID indicates an expected call of GetNoteByID.
func (mr *MocknoteGetterMockRecorder) GetNoteByID(ctx, noteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoteByID", reflect.TypeOf((*MocknoteGetter)(nil).GetNoteByID), ctx, noteID)
}

// GetNotesByType mocks base method.
func (m *MocknoteGetter) GetNotesByType(ctx context.Context, spaceID uuid.UUID, noteType model.NoteType) ([]model.GetNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotesByType", ctx, spaceID, noteType)
	ret0, _ := ret[0].([]model.GetNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotesByType indicates an expected call of GetNotesByType.
func (mr *MocknoteGetterMockRecorder) GetNotesByType(ctx, spaceID, noteType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotesByType", reflect.TypeOf((*MocknoteGetter)(nil).GetNotesByType), ctx, spaceID, noteType)
}

// GetNotesTypes mocks base method.
func (m *MocknoteGetter) GetNotesTypes(ctx context.Context, spaceID uuid.UUID) ([]model.NoteTypeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotesTypes", ctx, spaceID)
	ret0, _ := ret[0].([]model.NoteTypeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotesTypes indicates an expected call of GetNotesTypes.
func (mr *MocknoteGetterMockRecorder) GetNotesTypes(ctx, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotesTypes", reflect.TypeOf((*MocknoteGetter)(nil).GetNotesTypes), ctx, spaceID)
}

// MocknoteSearcher is a mock of noteSearcher interface.
type MocknoteSearcher struct {
	ctrl     *gomock.Controller
	recorder *MocknoteSearcherMockRecorder
}

// MocknoteSearcherMockRecorder is the mock recorder for MocknoteSearcher.
type MocknoteSearcherMockRecorder struct {
	mock *MocknoteSearcher
}

// NewMocknoteSearcher creates a new mock instance.
func NewMocknoteSearcher(ctrl *gomock.Controller) *MocknoteSearcher {
	mock := &MocknoteSearcher{ctrl: ctrl}
	mock.recorder = &MocknoteSearcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknoteSearcher) EXPECT() *MocknoteSearcherMockRecorder {
	return m.recorder
}

// SearchNoteByText mocks base method.
func (m *MocknoteSearcher) SearchNoteByText(ctx context.Context, req model.SearchNoteByTextRequest) ([]model.GetNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchNoteByText", ctx, req)
	ret0, _ := ret[0].([]model.GetNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchNoteByText indicates an expected call of SearchNoteByText.
func (mr *MocknoteSearcherMockRecorder) SearchNoteByText(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchNoteByText", reflect.TypeOf((*MocknoteSearcher)(nil).SearchNoteByText), ctx, req)
}

// MockuserService is a mock of userService interface.
type MockuserService struct {
	ctrl     *gomock.Controller
	recorder *MockuserServiceMockRecorder
}

// MockuserServiceMockRecorder is the mock recorder for MockuserService.
type MockuserServiceMockRecorder struct {
	mock *MockuserService
}

// NewMockuserService creates a new mock instance.
func NewMockuserService(ctrl *gomock.Controller) *MockuserService {
	mock := &MockuserService{ctrl: ctrl}
	mock.recorder = &MockuserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserService) EXPECT() *MockuserServiceMockRecorder {
	return m.recorder
}

// CheckUser mocks base method.
func (m *MockuserService) CheckUser(ctx context.Context, tgID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUser", ctx, tgID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUser indicates an expected call of CheckUser.
func (mr *MockuserServiceMockRecorder) CheckUser(ctx, tgID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUser", reflect.TypeOf((*MockuserService)(nil).CheckUser), ctx, tgID)
}

// MockauthService is a mock of authService interface.
type MockauthService struct {
	ctrl     *gomock.Controller
	recorder *MockauthServiceMockRecorder
}

// MockauthServiceMockRecorder is the mock recorder for MockauthService.
type MockauthServiceMockRecorder struct {
	mock *MockauthService
}

// NewMockauthService creates a new mock instance.
func NewMockauthService(ctrl *gomock.Controller) *MockauthService {
	mock := &MockauthService{ctrl: ctrl}
	mock.recorder = &MockauthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthService) EXPECT() *MockauthServiceMockRecorder {
	return m.recorder
}

// CheckToken mocks base method.
func (m *MockauthService) CheckToken(authHeader string) (*jwt.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckToken", authHeader)
	ret0, _ := ret[0].(*jwt.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckToken indicates an expected call of CheckToken.
func (mr *MockauthServiceMockRecorder) CheckToken(authHeader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckToken", reflect.TypeOf((*MockauthService)(nil).CheckToken), authHeader)
}

// GetPayload mocks base method.
func (m *MockauthService) GetPayload(token *jwt.Token) (jwt.MapClaims, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayload", token)
	ret0, _ := ret[0].(jwt.MapClaims)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetPayload indicates an expected call of GetPayload.
func (mr *MockauthServiceMockRecorder) GetPayload(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayload", reflect.TypeOf((*MockauthService)(nil).GetPayload), token)
}

// ParseToken mocks base method.
func (m *MockauthService) ParseToken(tokenString string) (*jwt.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseToken", tokenString)
	ret0, _ := ret[0].(*jwt.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseToken indicates an expected call of ParseToken.
func (mr *MockauthServiceMockRecorder) ParseToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseToken", reflect.TypeOf((*MockauthService)(nil).ParseToken), tokenString)
}
