definitions:
  model.CreateNoteRequest:
    properties:
      file:
        description: название файла в Minio (если есть)
        type: string
      space_id:
        description: айди пространства, куда сохранить заметку
        type: string
      text:
        description: текст заметки
        type: string
      type:
        allOf:
        - $ref: '#/definitions/model.NoteType'
        description: 'тип заметки: текстовая, фото, видео, етс'
      user_id:
        description: кто создал заметку
        type: integer
    type: object
  model.GetNote:
    properties:
      created:
        description: дата создания заметки в часовом поясе пользователя в unix
        type: string
      file:
        allOf:
        - $ref: '#/definitions/sql.NullString'
        description: название файла в Minio (если есть)
      id:
        type: string
      last_edit:
        $ref: '#/definitions/sql.NullTime'
      space_id:
        type: string
      text:
        type: string
      type:
        $ref: '#/definitions/model.NoteType'
      user_id:
        type: integer
    type: object
  model.Note:
    properties:
      created:
        description: дата создания заметки в часовом поясе пользователя в unix
        type: string
      file:
        description: название файла в Minio (если есть)
        type: string
      id:
        type: string
      last_edit:
        $ref: '#/definitions/sql.NullTime'
      space:
        allOf:
        - $ref: '#/definitions/model.Space'
        description: айди пространства, куда сохранить заметку
      text:
        description: текст заметки
        type: string
      type:
        allOf:
        - $ref: '#/definitions/model.NoteType'
        description: 'тип заметки: текстовая, фото, видео, етс'
      user:
        allOf:
        - $ref: '#/definitions/model.User'
        description: кто создал заметку
    type: object
  model.NoteType:
    enum:
    - text
    - photo
    type: string
    x-enum-varnames:
    - TextNoteType
    - PhotoNoteType
  model.NoteTypeResponse:
    properties:
      count:
        type: integer
      type:
        $ref: '#/definitions/model.NoteType'
    type: object
  model.Space:
    properties:
      created:
        description: указывается в часовом поясе пользователя-создателя
        type: string
      creator:
        description: айди пользователя-создателя в телеге
        type: integer
      id:
        type: string
      name:
        type: string
      personal:
        description: личное / совместное пространство
        type: boolean
    type: object
  model.UpdateNoteRequest:
    properties:
      file:
        description: название файла в Minio (если есть)
        type: string
      id:
        description: айди заметки
        type: string
      space_id:
        type: string
      text:
        description: новый текст
        type: string
      user_id:
        type: integer
    type: object
  model.User:
    properties:
      id:
        type: integer
      personal_space:
        $ref: '#/definitions/model.Space'
      tg_id:
        type: integer
      timezone:
        type: string
      username:
        type: string
    type: object
  sql.NullString:
    properties:
      string:
        type: string
      valid:
        description: Valid is true if String is not NULL
        type: boolean
    type: object
  sql.NullTime:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
info:
  contact: {}
  description: 'Веб-сервер, обрабатывающий запросы от Бота Зануды: управление заметками,
    а также перенаправление запросов к другим сервисам (напоминяний, пользователей)'
  title: Веб-сервер для Бота Зануды
paths:
  /health:
    get:
      description: Проверить состояние сервера и соединения
      responses:
        "200":
          description: OK
      summary: Проверить состояние сервера и соединения
  /spaces/{id}/notes:
    get:
      description: Запрос на получение всех заметок из личного пространства пользователя
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.GetNote'
            type: array
        "204":
          description: В пространстве отсутствют заметки
        "400":
          description: Невалидный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Пространства не существует
        "500":
          description: Внутренняя ошибка
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Запрос на получение всех заметок
  /spaces/{id}/notes/{type}:
    get:
      description: 'Получить все заметки определенного типа: текстовые, фото, етс'
      parameters:
      - description: ID пространства
        in: path
        name: id
        required: true
        type: string
      - description: 'тип заметки: текст, фото, етс'
        in: path
        name: type
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.GetNote'
            type: array
        "204":
          description: Нет заметок
        "400":
          description: Невалидный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Внутренняя ошибка
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить все заметки одного типа
  /spaces/{id}/notes/types:
    get:
      description: Получить список всех типов заметок и их количество
      parameters:
      - description: ID пространства
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.NoteTypeResponse'
            type: array
        "204":
          description: Нет заметок
        "400":
          description: Невалидный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Внутренняя ошибка
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить все типы заметок
  /spaces/notes/create:
    post:
      description: Запрос на создание заметки с текстом. Создается в указанном пространстве
      parameters:
      - description: |-
          создать заметку:
          указать айди пользователя,
          айди его личного / совместного пространства,
          текст заметки
          тип заметки: текстовый, фото, видео, и т.п.
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateNoteRequest'
      responses:
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Невалидный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Внутренняя ошибка
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Запрос на создание заметки
  /spaces/notes/update:
    patch:
      description: Запрос на обновление заметки с текстом. Создается в указанном пространстве
      parameters:
      - description: |-
          обновить заметку:
          указать айди пользователя,
          айди его личного / совместного пространства,
          новый текст заметки,
          тип заметки: текст, фото, етс
          айди заметки, которую нужно обновить
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UpdateNoteRequest'
      responses:
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Невалидный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Внутренняя ошибка
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Запрос на обновление заметки
swagger: "2.0"
