info:
  contact: {}
  description: 'Веб-сервер, обрабатывающий запросы от Бота Зануды: управление заметками,
    а также перенаправление запросов к другим сервисам (напоминяний, пользователей)'
  title: Веб-сервер для Бота Зануды
paths:
  /health:
    get:
      description: Проверить состояние сервера и соединения
      responses:
        "200":
          description: OK
      summary: Проверить состояние сервера и соединения
swagger: "2.0"
